# ****************************************************************************
#   Project:  Feographia
#   Purpose:  The application to work with the biblical text
#   Author:   NikitaFeodonit, nfeodonit@yandex.com
# ****************************************************************************
#     Copyright (c) 2017-2020 NikitaFeodonit
#
#     This file is part of the Feographia project.
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published
#     by the Free Software Foundation, either version 3 of the License,
#     or (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#     See the GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program. If not, see <http://www.gnu.org/licenses/>.
# ****************************************************************************

# === Windows builds ===

image:
  - Visual Studio 2017
  - Visual Studio 2015


environment:
  global:
    cmr_APP_NAME: Feographia
    cmr_BUILD_TESTING: ON

    cmr_REPO_DIR: ${APPVEYOR_BUILD_FOLDER}
    cmr_WORK_DIR: ${cmr_REPO_DIR}

    cmr_BUILD_DIR: ${cmr_WORK_DIR}\build
    cmr_INSTALL_DIR: ${cmr_BUILD_DIR}\install
    cmr_DOWNLOAD_DIR: ${cmr_BUILD_DIR}\download

    cmr_CMAKE_BUILD_TYPE: Release

    cmr_CMAKE_VERSION: 3.11
    cmr_CMAKE_RELEASE: cmake-${cmr_CMAKE_VERSION}.0-win64-x64
    cmr_CMAKE_DIR: ${cmr_INSTALL_DIR}\${cmr_CMAKE_RELEASE}
    cmr_CMAKE_CMD: cmake
    cmr_CTEST_CMD: ctest

    cmr_MinGW_w64_ROOT_PATH: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1

    PATH: ${cmr_INSTALL_DIR}\bin;${cmr_CMAKE_DIR}\bin;%PATH%

    cmr_JOBS_CNT: 4

  matrix:
    # MSVC 2017, x64, shared
    - cmr_MSVC_2017_x64_shared: ON
      cmr_GENERATOR:    -DCMAKE_GENERATOR:STRING="Visual Studio 15 2017"
      cmr_GEN_PLATFORM: -DCMAKE_GENERATOR_PLATFORM:STRING="x64"
      cmr_GEN_TOOLSET:  -DCMAKE_GENERATOR_TOOLSET:STRING="v141,host=x64"
      cmr_CONFIG_TYPES: -DCMAKE_CONFIGURATION_TYPES:STRING=${cmr_CMAKE_BUILD_TYPE}
      cmr_STD_LIBS:
      cmr_BUILD_SHARED_LIBS: ON

    # MSVC 2017, x64, static
    - cmr_MSVC_2017_x64_static: ON
      cmr_GENERATOR:    -DCMAKE_GENERATOR:STRING="Visual Studio 15 2017"
      cmr_GEN_PLATFORM: -DCMAKE_GENERATOR_PLATFORM:STRING="x64"
      cmr_GEN_TOOLSET:  -DCMAKE_GENERATOR_TOOLSET:STRING="v141,host=x64"
      cmr_CONFIG_TYPES: -DCMAKE_CONFIGURATION_TYPES:STRING=${cmr_CMAKE_BUILD_TYPE}
      cmr_STD_LIBS:
      cmr_BUILD_SHARED_LIBS: OFF

    # MSVC 2017, x32, shared
    - cmr_MSVC_2017_x32_shared: ON
      cmr_GENERATOR:    -DCMAKE_GENERATOR:STRING="Visual Studio 15 2017"
      cmr_GEN_PLATFORM: -DCMAKE_GENERATOR_PLATFORM:STRING="Win32"
      cmr_GEN_TOOLSET:  -DCMAKE_GENERATOR_TOOLSET:STRING="v141,host=x64"
      cmr_CONFIG_TYPES: -DCMAKE_CONFIGURATION_TYPES:STRING=${cmr_CMAKE_BUILD_TYPE}
      cmr_STD_LIBS:
      cmr_BUILD_SHARED_LIBS: ON

    # MSVC 2017, x32, static
    - cmr_MSVC_2017_x32_static: ON
      cmr_GENERATOR:    -DCMAKE_GENERATOR:STRING="Visual Studio 15 2017"
      cmr_GEN_PLATFORM: -DCMAKE_GENERATOR_PLATFORM:STRING="Win32"
      cmr_GEN_TOOLSET:  -DCMAKE_GENERATOR_TOOLSET:STRING="v141,host=x64"
      cmr_CONFIG_TYPES: -DCMAKE_CONFIGURATION_TYPES:STRING=${cmr_CMAKE_BUILD_TYPE}
      cmr_STD_LIBS:
      cmr_BUILD_SHARED_LIBS: OFF

    # MSVC 2017, WinXP, shared
    - cmr_MSVC_2017_WinXP_shared: ON
      cmr_GENERATOR:    -DCMAKE_GENERATOR:STRING="Visual Studio 15 2017"
      cmr_GEN_PLATFORM: -DCMAKE_GENERATOR_PLATFORM:STRING="Win32"
      cmr_GEN_TOOLSET:  -DCMAKE_GENERATOR_TOOLSET:STRING="v141_xp,host=x64"
      cmr_CONFIG_TYPES: -DCMAKE_CONFIGURATION_TYPES:STRING=${cmr_CMAKE_BUILD_TYPE}
      cmr_STD_LIBS:
      cmr_BUILD_SHARED_LIBS: ON

    # MSVC 2017, WinXP, static
    - cmr_MSVC_2017_WinXP_static: ON
      cmr_GENERATOR:    -DCMAKE_GENERATOR:STRING="Visual Studio 15 2017"
      cmr_GEN_PLATFORM: -DCMAKE_GENERATOR_PLATFORM:STRING="Win32"
      cmr_GEN_TOOLSET:  -DCMAKE_GENERATOR_TOOLSET:STRING="v141_xp,host=x64"
      cmr_CONFIG_TYPES: -DCMAKE_CONFIGURATION_TYPES:STRING=${cmr_CMAKE_BUILD_TYPE}
      cmr_STD_LIBS:
      cmr_BUILD_SHARED_LIBS: OFF

    # MSVC 2015, x64, shared
    - cmr_MSVC_2015_x64_shared: ON
      cmr_GENERATOR:    -DCMAKE_GENERATOR:STRING="Visual Studio 14 2015"
      cmr_GEN_PLATFORM: -DCMAKE_GENERATOR_PLATFORM:STRING="x64"
      cmr_GEN_TOOLSET:  -DCMAKE_GENERATOR_TOOLSET:STRING="v140,host=x64"
      cmr_CONFIG_TYPES: -DCMAKE_CONFIGURATION_TYPES:STRING=${cmr_CMAKE_BUILD_TYPE}
      cmr_STD_LIBS:
      cmr_BUILD_SHARED_LIBS: ON

    # MSVC 2015, x64, static
    - cmr_MSVC_2015_x64_static: ON
      cmr_GENERATOR:    -DCMAKE_GENERATOR:STRING="Visual Studio 14 2015"
      cmr_GEN_PLATFORM: -DCMAKE_GENERATOR_PLATFORM:STRING="x64"
      cmr_GEN_TOOLSET:  -DCMAKE_GENERATOR_TOOLSET:STRING="v140,host=x64"
      cmr_CONFIG_TYPES: -DCMAKE_CONFIGURATION_TYPES:STRING=${cmr_CMAKE_BUILD_TYPE}
      cmr_STD_LIBS:
      cmr_BUILD_SHARED_LIBS: OFF

    # MinGW-w64, x64, shared
    - cmr_MinGW_w64_x64_shared: ON
      cmr_GENERATOR:    -DCMAKE_GENERATOR:STRING="MinGW Makefiles"
      cmr_GEN_PLATFORM:
      cmr_GEN_TOOLSET:
      cmr_CONFIG_TYPES:
      cmr_STD_LIBS:
      cmr_BUILD_SHARED_LIBS: ON
      cmr_CMAKE_VERSION: 3.4
      cmr_CMAKE_RELEASE: cmake-${cmr_CMAKE_VERSION}.0-win32-x86
      MINGW_HOME: ${cmr_MinGW_w64_ROOT_PATH}\mingw64
      PATH: ${cmr_INSTALL_DIR}\bin;${cmr_CMAKE_DIR}\bin;${MINGW_HOME}\bin;%PATH%

    # MinGW-w64, x64, static
    - cmr_MinGW_w64_x64_static: ON
      cmr_GENERATOR:    -DCMAKE_GENERATOR:STRING="MinGW Makefiles"
      cmr_GEN_PLATFORM:
      cmr_GEN_TOOLSET:
      cmr_CONFIG_TYPES:
      cmr_STD_LIBS: -DCMAKE_C_STANDARD_LIBRARIES:STRING="-static" -DCMAKE_CXX_STANDARD_LIBRARIES:STRING="-static"
      cmr_BUILD_SHARED_LIBS: OFF
      cmr_CMAKE_VERSION: 3.4
      cmr_CMAKE_RELEASE: cmake-${cmr_CMAKE_VERSION}.0-win32-x86
      MINGW_HOME: ${cmr_MinGW_w64_ROOT_PATH}\mingw64
      PATH: ${cmr_INSTALL_DIR}\bin;${cmr_CMAKE_DIR}\bin;${MINGW_HOME}\bin;%PATH%


matrix:
  exclude:
    - image: Visual Studio 2015
      cmr_MSVC_2017_x64_shared: ON

    - image: Visual Studio 2015
      cmr_MSVC_2017_x64_static: ON

    - image: Visual Studio 2015
      cmr_MSVC_2017_x32_shared: ON

    - image: Visual Studio 2015
      cmr_MSVC_2017_x32_static: ON

    - image: Visual Studio 2015
      cmr_MSVC_2017_WinXP_shared: ON

    - image: Visual Studio 2015
      cmr_MSVC_2017_WinXP_static: ON

    - image: Visual Studio 2015
      cmr_MinGW_w64_x64_shared: ON

    - image: Visual Studio 2015
      cmr_MinGW_w64_x64_static: ON

    - image: Visual Studio 2017
      cmr_MSVC_2015_x64_shared: ON

    - image: Visual Studio 2017
      cmr_MSVC_2015_x64_static: ON


# TODO: remove it after fix this build.
#    - image: Visual Studio 2017
#      cmr_MinGW_w64_x64_shared: ON


clone_folder: c:\projects\${cmr_APP_NAME}


before_build:
  - ver
  - ps: $env:PATH = $env:PATH -replace "C:\\Program Files\\Git\\usr\\bin",""

  - mkdir %cmr_BUILD_DIR%
  - mkdir %cmr_INSTALL_DIR%
  - mkdir %cmr_DOWNLOAD_DIR%

  - curl -fsS -o %cmr_DOWNLOAD_DIR%\%cmr_CMAKE_RELEASE%.zip https://cmake.org/files/v%cmr_CMAKE_VERSION%/%cmr_CMAKE_RELEASE%.zip
  - 7z.exe x -aoa -o%cmr_INSTALL_DIR% %cmr_DOWNLOAD_DIR%\%cmr_CMAKE_RELEASE%.zip


build_script:
  - cd %cmr_BUILD_DIR%

  - cmake --version

  - cmake %cmr_SAMPLE_DIR%
      -Dcmr_BUILD_MULTIPROC_CNT:STRING=%cmr_JOBS_CNT%
      -Dcmr_PRINT_DEBUG:BOOL=ON
      -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
      -DCMAKE_COLOR_MAKEFILE:BOOL=ON
      -DBUILD_TESTING:BOOL=%cmr_BUILD_TESTING%
      -DCMAKE_INSTALL_PREFIX:PATH=%cmr_INSTALL_DIR%
      -Dcmr_DOWNLOAD_DIR:PATH=%cmr_DOWNLOAD_DIR%
      -Dcmr_UNPACKED_DIR:PATH=%cmr_DOWNLOAD_DIR%\unpacked
        -DCMAKE_BUILD_TYPE:STRING=%cmr_CMAKE_BUILD_TYPE%
        -DBUILD_SHARED_LIBS:BOOL=%cmr_BUILD_SHARED_LIBS%
      %cmr_GENERATOR% %cmr_GEN_PLATFORM% %cmr_GEN_TOOLSET% %cmr_CONFIG_TYPES% %cmr_STD_LIBS%

  - cmake --build . --config %cmr_CMAKE_BUILD_TYPE%

  - ctest --output-on-failure --build-config %cmr_CMAKE_BUILD_TYPE%


# === Notifications ===

notifications:
  - provider: Email
    to:
      - nfeodonit@yandex.com
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
